services:
    braunedigital.cache.listener.cache:
        class: BrauneDigital\CacheBundle\EventListener\CacheListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preUpdate }